spring:
  datasource:
    url: jdbc:hsqldb:db/test/blog;hsqldb.write_delay=false
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbcDriver
    data: classpath:database/prod_data.sql
  jpa:
    database-platform: HSQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: info
    com.aabramov: debug