DELETE FROM POSTS_TAGS;
DELETE FROM COMMENTS;
DELETE FROM POSTS;
DELETE FROM USERS_FAVOURITE_TAGS;
DELETE FROM TAGS;
DELETE FROM COLORS;
DELETE FROM USERS;

INSERT INTO USERS (ID, EMAIL, PASSWORD, USERNAME) VALUES
  (1, 'email1@example.com', 'password1', 'user1'),
  (2, 'email2@example.com', 'password2', 'user2');

INSERT INTO POSTS (ID, BODY, CREATION_DATE, TITLE, AUTHOR_ID) VALUES
  (1, 'body1', NULL, 'title1', 1),
  (2, 'body2', NULL, 'title2', 1),
  (3, 'body3', NULL, 'title3', 2);

INSERT INTO COMMENTS (ID, BODY, CREATION_DATE, AUTHOR_ID, POST_ID) VALUES
  (1, 'comment1', NULL, 1, 1),
  (2, 'comment2', NULL, 2, 1),
  (3, 'comment3', NULL, 1, 1);