DELETE FROM POSTS_TAGS;
DELETE FROM COMMENTS;
DELETE FROM POSTS;
DELETE FROM USERS_FAVOURITE_TAGS;
DELETE FROM TAGS;
DELETE FROM COLORS;
DELETE FROM USERS;

INSERT INTO COLORS (ID, HEX, COLOR_NAME) VALUES (1, '#FF0000', 'Red');
INSERT INTO COLORS (ID, HEX, COLOR_NAME) VALUES (2, '#00FF00', 'Green');

INSERT INTO TAGS (ID, NAME, COLOR_ID) VALUES (1, 'test-tag-1', 1);
INSERT INTO TAGS (ID, NAME, COLOR_ID) VALUES (2, 'test-tag-2', 2);